export enum CHANNEL {
  APP_INFO = 'app:info',
  PRINT_TEST = 'print:test',
  PRINT = 'print',
  LOGIN = 'login',
  BACKUP = 'backup',
  QUIT = 'quit',
  FIND_MEMBERSHIP = 'find:membership',
  FIND_DUPLICATE_ACCOUNT = 'find:duplicate:account',
  ADD_MEMBERSHIP = 'add:membership',
  LAST_RECORD = 'last:record',
  DELETE_MEMBERSHIP = 'delete:membership',
  EDIT_MEMBERSHIP = 'edit:membership',
  BUY_GALLON = 'buy:gallon',
  AUTHENTICATE = 'authenticate',
  RENEW_GALLON = 'renew:gallon',
  PRINT_REPORT = 'print:report',
  HISTORY = 'history',
}
